# Generated by Django 3.0.5 on 2020-04-25 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія для публікації', 'verbose_name_plural': 'Категорії для публікацій'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 4, 25, 19, 56, 26, 549977, tzinfo=utc), verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Показувати на головній сторінці', verbose_name='Головна'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 4, 25, 19, 56, 26, 549977, tzinfo=utc), unique_for_date='pub_date', verbose_name='Слаг'),
        ),
    ]
